### ISSUE TITLE
Make detach opt-in rather than opt-out

### ISSUE THREAD

**Issue by Didgeridoohan** [Magisk-Modules-Repo/iYTBP-Vanced-Magisk-Repo#2]
The detach feature of the module is nice, but it has it's issues.

On my OnePlus 3T it detaches YouTube from the Play Store, but it also breaks auto updates for all other apps. Re-attaching with the provided files and script doesn't work and a complete reset of the Play Store is necessary to bring back full functionality.

Running the detach script gives the following output:
```
Process output: /sbin/.core/img/iYTBP-Vanced-Magisk-Repo/post-fs-data.sh
Exit status: 0
Output:
cmd: Failure calling service activity: Failed transaction (2147483646)
Error Output:
Error: java.lang.IllegalArgumentException: Component class com.google.android.finsky.dailyhygiene.DailyHygieneDailyHygieneService'
	pm enable com.android.vending/com.google.android.finsky.hygiene.DailyHygiene$DailyHygieneService' does not exist in com.android.vending
```

Please keep the detach feature off by default and let users enable it if they want it.

**Comment by sjayminsgithub** [comment]
Hi @zanezam,

I completely agree with what @Didgeridoohan said, if you could remove the feature or at least make it optional, it will be really good who get updates from Google Play Store.

Also another thing I'd say is that you're adding a file to /data root. AFAIK, adding files to /data root breaks MagiskHide policies, that's the reason why magisk.img was moved to /data/adb, so if you choose to not remove but make the feature optional, you should locate the enable / disable files in the mod_dir instead of /data root.

And finally, there is a bug in your post-fs-data script, you are checking for both enable and disable file in their independant sub process, which will cause them both to conflict each others functionalities, so you should better put an if...elif...fi... statement there for both of them in a single sub process.

**Comment by zanezam** [comment]
thx @Didgeridoohan for the headsup wasn't aware that detach broke other app auto updates! personally i don't use it on any device so i didn't notice. Second, yes good point to disable the detach per default. tbh i rather would like to remove that whole feature as i think it doesn't belong in here and should be done separately it only is in because of multiple user request. i did provide an alternative for them but that was "too complicated" for them. that change now by opting in might rise up complains again but well i agree so i will do it... or better said @sjayminsgithub will do it! many many thx for improving my whole "one shot shit" looks good and i will put it in after testing (of course i assume u did test but well control is better u know *g*)! here also a side note: i didn't have any issues with magisk hide by putting files into /data on multiple devices otherwise i would have searched for a better place to put them. ;)

**Comment by Didgeridoohan** [comment]
@zanezam It seems like the Play Store breaking only happens for some users.

I'm sure there will be some user complaints, but a feature that breaks some users devices in such a way should definitely be opt-in...

**Comment by zanezam** [comment]
improvements tested and merged. thx again @sjayminsgithub 
closing this now.

**Comment by sjayminsgithub** [comment]
You're always welcome!
